version: "3.0"

services:
  mysqldb:
    image: mysql:5.7
    container_name: auction_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  # Setup Node Container
  server:
    build: ./server
    container_name: auction_api
    expose:
      - ${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/app/server/
      - ./server/node_modules:/app/server/node_modules
      - ./server/.env:/app/server/.env
    command: npm run start
    depends_on:
      - redis
    env_file:
      - ./server/.env

  # Setup React Container
  client:
    build: ./client
    container_name: auction_ui
    expose:
      - ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/:/app/client/
      - /app/client/node_modules
      - ./client/.env:/app/client/.env
    links:
      - server
    env_file:
      - ./client/.env
    command: npm run start:dev

  # Setup Redis Container
  redis:
    container_name: auction_redis
    image: redis:5.0.1-alpine
    ports:
      - 6379:6379
    volumes:
      - .data/redis:/data

volumes: 
  db:

networks:
    default:
        external:
            name: ${D_SERVICES_NETWORK}

